### ISSUE TITLE
Error in rnaseq.rules

### ISSUE THREAD

**Issue by PierreL-B** [sequana/rnaseq#12]
Hi Thomas,

I just came across a typo in rnaseq.rules, line 279:
Instead of 
"adapter_tool = manager.config.cutadapt.software_choice",
which returns an error for now, it should be:
"adapter_tool = manager.config.trimming.software_choice"

Happy New Year !
Cheers,
Pierre

**Comment by cokelaer** [comment]
Hi Pierre, happy new year as well ! 
well spotted. Indeed, this is a typo. 
We are now exclusively using fastp for trimming and adapter removal, which explain why we have not seen this issue. I'll try to add a test to catch this regression bug.  I'll do a release in a couple of days to fix this issue. I'll let you know once on github and pypi
cheers

**Comment by cokelaer** [comment]
The new pipelines is now online on pypi (v0.15.0)
